defaultProject: abhi-demobox
defaultLocation: australia-southeast1
defaultDataset: dataform_tryout
defaultAssertionDataset: dataform_tryout_assertions
vars:
    RAW_DATA: dataform_tryout
    CURATED_DATA: dataform_tryout