defaultProject: abhi-demobox
defaultLocation: US
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
vars:
    RAW_DATA: dataform_gkg_raw
    CURATED_DATA: dataform_gkg_curated